-- 코드를 입력하세요
SELECT A.MEMBER_ID
     , A.MEMBER_NAME
     , A.GENDER
     , TO_CHAR(A.DATE_OF_BIRTH, 'YYYY-MM-DD') DATE_OF_BIRTH
  FROM MEMBER_PROFILE A
 WHERE 1=1
   --AND A.DATE_OF_BIRTH          = ''
   AND A.GENDER                 = 'W'
   --AND SUBSTR(TO_CHAR(A.DATE_OF_BIRTH, 'YYYYMMDD'), 5, 2) = '03'
   AND EXTRACT(MONTH FROM A.DATE_OF_BIRTH) = '3'
   AND A.TLNO                   IS NOT NULL
 ORDER BY A.MEMBER_ID 
